# Define como se ejecutan y se comunican entre si los contenedores
# version Docker Compose
version: "3.9"


# ------------------------------------------------------------
# Definición de servicios
# ------------------------------------------------------------
services:
  # ----------------------------------------------------------
  # Base de datos (PostgreSQL)
  # ----------------------------------------------------------
  db:
    image: postgres:16                        # Usa la imagen de Postgres versión 16
    container_name: cloudops-db               # Nombre del contenedor
    environment:                              # Variables de entorno para configurar la DB
      POSTGRES_USER: ${DB_USER:-cloudops}                         # Usuario de la base de datos
      POSTGRES_PASSWORD: ${DB_PASSWORD:-cloudops}                 # Contraseña del usuario
      POSTGRES_DB: ${DB_NAME:-cloudops}                           # Nombre de la base de datos
    volumes:
      - db_data:/var/lib/postgresql/data                          # Volumen para persistir los datos
    healthcheck:                              # Comprueba si el servicio está listo
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]      # Usa el comando pg_isready para definir la condición de salud del contenedor
      interval: 10s                                               # Repite la comprobación cada 10 segundos
      timeout: 5s                                                 # Espera máximo 5 segundos por respuesta
      retries: 5                                                  # Reintenta 5 veces antes de marcar como "no saludable"
    networks: [app_net]                       # Conecta el contenedor a la red interna "app_net"


  # ----------------------------------------------------------
  # Aplicación Flask (backend)
  # ----------------------------------------------------------
  app:
    build:                                    # Construye la imagen a partir del Dockerfile
      context: .                                                  # Carpeta raíz del proyecto
      dockerfile: app/Dockerfile                                  # Ruta del Dockerfile dentro del proyecto
    container_name: cloudops-app              # Nombre del contenedor
    env_file:
      - app/.env.example                                          # Carga variables de entorno desde el archivo .env.example
    depends_on:                               # Espera a que la base de datos esté lista antes de arrancar
      db:
        condition: service_healthy
    ports:
      - "8000:8000"                                               # Expone el puerto 8000 para acceder a la app desde el host
    networks: [app_net]                       # Conecta con la misma red que la base de datos y Nginx

  # ----------------------------------------------------------
  # Nginx (proxy inverso)
  # ----------------------------------------------------------
  nginx:
    image: nginx:1.27-alpine                  # Imagen  ligera de Nginx
    container_name: cloudops-nginx            # Nombre del contenedor
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro    # Monta la configuración personalizada
    depends_on:
      - app                                  # Espera a que la app esté disponible
    ports:
      - "80:80"                                                   # Expone el puerto 80
    networks: [app_net]                      # Usa la misma red para comunicarse con la app

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: cloudops-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=15d"
      - "--web.enable-lifecycle"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    ports:
      - "9090:9090"
    networks: [app_net]
    depends_on:
      - app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9090/-/healthy"]
      interval: 15s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:11.2.2
    container_name: cloudops-grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    depends_on:
      - prometheus
    networks: [app_net]
    restart: unless-stopped


  node_exporter:
    image: prom/node-exporter:v1.8.2
    container_name: cloudops-node-exporter
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks: [app_net]
    restart: unless-stopped



  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cloudops-cadvisor
    ports:
      - "8081:8080"    # UI cadvisor (opcional); Prometheus scrapea en :8080/metrics
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks: [app_net]
    restart: unless-stopped

volumes:
  db_data:
  prom_data:
  grafana_data:

networks:
  app_net:
    driver: bridge                           # Tipo de red: "bridge" (comunicación interna entre contenedores)