# -------------------------------------------------------------------
# Configuración global de Prometheus
# -------------------------------------------------------------------
global:
  scrape_interval: 15s        # Cada cuánto Prometheus recoge métricas
  evaluation_interval: 30s    # Cada cuánto se evalúan reglas internas (si existieran)
  scrape_timeout: 10s         # Tiempo máximo permitido para obtener métricas
  external_labels:            # Etiquetas añadidas a TODAS las series almacenadas
    project: cloudops-orchestrator   # Identificador global del proyecto

# -------------------------------------------------------------------
# Definición de trabajos (scrape jobs)
# -------------------------------------------------------------------
scrape_configs:

  # ---------------------------------------------------------------
  # MÉTRICAS DE LA APP FLASK
  # ---------------------------------------------------------------
  - job_name: "flask_app"          # Nombre del job en Prometheus
    metrics_path: /metrics         # Ruta específica donde la app expone sus métricas
    static_configs:
      - targets: ["app:8000"]      # contenedor "app", puerto 8000
        labels:
          service: "app"           # Etiqueta custom que categoriza el servicio
          layer: "backend"         # Etiqueta que indica la capa lógica

  # ---------------------------------------------------------------
  # MÉTRICAS DEL NODE EXPORTER (HOST / SISTEMA)
  # ---------------------------------------------------------------
  - job_name: "node_exporter"      # Nombre del job
    static_configs:
      - targets: ["node_exporter:9100"]   # Contenedor node_exporter expone métricas en 9100

    relabel_configs:
      # Regla para modificar etiquetas antes de guardar métricas
      # En este caso, sobrescribe el valor de "instance" y lo simplifica
      - target_label: instance
        replacement: "host"         # Así en lugar de un nombre largo aparecerá "host"

  # ---------------------------------------------------------------
  # MÉTRICAS DE cADVISOR (CONTENEDORES DOCKER)
  # ---------------------------------------------------------------
  - job_name: "cadvisor"             # Nombre del job
    static_configs:
      - targets: ["cadvisor:8080"]   # cAdvisor expone métricas en su puerto interno 8080
        labels:
          service: "cadvisor"        # Etiqueta que clasifica estas métricas como del servicio cadvisor
          layer: "containers"        # Indica que son métricas relacionadas con contenedores
