{
 "title": "CloudOps - App",
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests per second (by endpoint)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    { "expr": "rate(app_requests_total[5m])", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Total requests /",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "app_requests_total{endpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Total requests /health",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "app_requests_total{endpoint=\"/health\"}"
    }
   ]
  }
 ]
}